while True:
    print("Введите A,B,C")
    a=float(input())
    b=float(input())
    c=float(input())
    AC=abs(a-c)
    BC=abs(b-c)
    print("AC=" + str(AC))
    print("BC=" + str(BC))
    print("AC+BC=" + str(AC+BC))
