while True: #Цикл
    print("Введите 2 ненулевых числа")
    a=float(input())
    b=float(input())
    print("Сумма=" + str(a**2+b**2))
    print("a^2-b^2=" + str(a**2-b**2))
    print("b^2-a^2=" + str(b**2-a**2))
    print("Произведение=" + str((a**2)*b**2))
    print("a^2/b^2=" + str(a**2/b**2))
    print("b^2/a^2=" + str(b**2/a**2))
