while True:
    print("Введите x1")
    x1=float(input())
    print("Введите y1")
    y1=float(input())
    print("Введите x2")
    x2=float(input())
    print("Введите y2")
    y2=float(input())
    a=abs(x1-x2)
    b=abs(y1-y2)
    print("P=" + str(2*(a+b)))
    print("S=" + str(a*b))
